### ISSUE TITLE
[Bug] wrong denominator

### ISSUE THREAD

**Issue by aben20807** [aben20807/assign_5_18#2]
https://github.com/aben20807/assign_5_18/blob/bcd7dea8496319dcb02b1f951614eac5f85ee0c2/test_poly.c#L55
Should be `(TEST_TIMES * 9 / 10)`, because it top and tail the 5% extreme value.

**Comment by krimson8** [comment]
2047e7f34172b3ef3e0a2f70f3ddb6db2327209b
Amended the above line of code.
